import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header"; // Import Header
import Footer from "@/components/Footer"; // Import Footer
import GridPattern from "@/components/magicui/grid-pattern"; // Corrected Import Path
import { CartProvider } from "@/context/CartContext"; // Import CartProvider
import { cn } from "@/lib/utils"; // Import cn utility
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable, "antialiased")}>
        <CartProvider> {/* Wrap content with CartProvider */}
          <div className="relative flex flex-col min-h-screen">
            {/* Add GridPattern as a background */}
            <GridPattern
            width={40}
            height={40}
            x={-1}
            y={-1}
            className={cn(
              "[mask-image:linear-gradient(to_bottom_right,white,transparent,transparent)] ",
              "absolute inset-0 h-full w-full stroke-gray-200 dark:stroke-gray-800",
            )}
          />
          {/* Ensure content is above the pattern */}
          <div className="relative z-10 flex flex-col flex-grow">
            <Header />
            <main className="flex-grow container mx-auto px-4 py-8">
              {children}
            </main>
            <Footer />
          </div>
        </div>
       </CartProvider> {/* Close CartProvider */}
      </body>
    </html>
  );
}
